This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./ba.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ba.acn....done (269 entries accepted, 0 rejected).
Sorting entries.....done (2309 comparisons).
Generating output file ba.acr....done (197 lines written, 0 warnings).
Output written in ba.acr.
Transcript written in ba.alg.
