This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (57 entries accepted, 0 rejected).
Sorting entries....done (345 comparisons).
Generating output file thesis.acr....done (62 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
